model:
  name: langcell
  cell_model: /data/Mamba/Project/Single_Cell/Benchmark/Cell_Type/LangCell/ckpt/cell_bert
  cell_proj: /data/Mamba/Project/Single_Cell/Benchmark/Cell_Type/LangCell/ckpt/cell_proj.bin
  text_tokenizer: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
  text_model: /data/Mamba/Project/Single_Cell/Benchmark/Cell_Type/LangCell/ckpt/text_bert
  text_proj: /data/Mamba/Project/Single_Cell/Benchmark/Cell_Type/LangCell/ckpt/text_proj.bin
  ctm_head: /data/Mamba/Project/Single_Cell/Benchmark/Cell_Type/LangCell/ckpt/ctm_head.bin