model:
  name: molcraft
  ligand_atom_feature_dim: 13
  protein_atom_feature_dim: 27
  node_indicator: true
  hidden_dim: 128
  unio2net:
    num_blocks: 1
    num_layers: 9
    hidden_dim: 128
    n_heads: 16
    edge_feat_dim: 4  # edge type feat
    num_r_gaussian: 20
    knn: 32 # !
    num_node_types: 8
    act_fn: relu
    norm: True
    cutoff_mode: knn  # [radius, none]
    ew_net_type: global  # [r, m, none]
    num_x2h: 1
    num_h2x: 1
    r_max: 10.
    x2h_out_fc: False
    sync_twoup: False
  sigma1_coord: 0.03
  beta1: 1.5
  pos_norm: 2.0
  num_sample_steps: 100

dataset:
  pocket_only: true
  debug: true

evaluation:
  num_test_repeats: 100